[project]
name = "customer-satisfaction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "zenml[server]>=0.84.0",
]
